server.port=9090

spring.application.name=config

spring.cloud.config.server.git.uri=https://github.com/julia-209/git-config-repozitory
spring.cloud.config.server.git.search-paths={application}

spring.cloud.config.server.encrypt.enabled=true
encrypt.key=etgf66ko