server:
  port: 9000

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: myproject
        uri: lb://myproject
        predicates:
          - Path=/myproject/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

